// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using SampleApp.iOS.ViewControllers.DetailViewControllers;
using UIKit;

namespace SampleApp.iOS
{
	public partial class ItemDetailViewController : UIViewController
	{
		public ItemDetailViewModel ViewModel { get; set; }

		public ItemDetailViewController (IntPtr handle) : base (handle)
		{

		}

		public override void ViewDidLoad()
        {
			DescriptionTextView.Text = (string) ViewModel.ConfigItem.FullDetails;
			NameLabel.Text = ViewModel.ConfigItem.Name;
        }
	}
}
