// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreAnimation;
using CoreGraphics;
using Foundation;
using SampleApp.iOS.ViewControllers.DetailViewControllers;
using SampleApp.Models;
using UIKit;

namespace SampleApp.iOS
{
    public partial class ItemCollectionViewcController
    {
        private class ItemDataSource : UICollectionViewDataSource
        {
            static readonly NSString CELL_IDENTIFIER = new NSString("COLLECTION_ITEM");


            public Platforms platforms;

            public ItemDataSource(ItemDetailViewModel ViewModel)
            {
                platforms = (Platforms)ViewModel.ConfigItem.FullDetails;
            }

        


            public override UICollectionViewCell GetCell(UICollectionView collectionView, NSIndexPath indexPath)
            {
                var cell = (ItemCollectionViewCell) collectionView.DequeueReusableCell(CELL_IDENTIFIER, indexPath);

                string name;
                switch (indexPath.Row)
                {
                    case 0:
                        name = "Android";
                        break;
                    case 1:
                        name = "iOS";
                        break;
                    default:
                        name = "Web";
                        break;
                }


                cell.LayoutMargins = UIEdgeInsets.Zero;

                var gradient = new CAGradientLayer();
                gradient.Frame = cell.Bounds;
                CGColor[] array = { UIColor.White.CGColor, UIColor.Yellow.CGColor, UIColor.White.CGColor };
                gradient.Colors = array;
                cell.Layer.InsertSublayer(gradient, 0);

                cell.InitViews(name);

                return cell;
            }

            public override nint GetItemsCount(UICollectionView collectionView, nint section)
            {
                return 3;
            }
        }
    }
}
