// This file has been autogenerated from a class added in the UI designer.

using CoreGraphics;
using Foundation;
using Newtonsoft.Json;
using SampleApp.iOS.ViewControllers.DetailViewControllers;
using SampleApp.Models;
using UIKit;

namespace SampleApp.iOS
{
    public partial class ItemCollectionViewcController
    {
        private class ItemDeletgateFlowLayout : UICollectionViewDelegateFlowLayout
        {
            public Platforms platforms;
            public ItemCollectionViewcController ViewController;

            public ItemDeletgateFlowLayout(ItemDetailViewModel ViewModel, ItemCollectionViewcController viewcController)
            {
                platforms = (Platforms)ViewModel.ConfigItem.FullDetails;
                ViewController = viewcController;
            }

            public override CGSize GetSizeForItem(UICollectionView collectionView, UICollectionViewLayout layout, NSIndexPath indexPath)
            {
                var padding = 25;
                var cellSize = collectionView.Frame.Size.Width - padding;
                return new CGSize(cellSize / 2, cellSize / 2);
            }

            public override void ItemSelected(UICollectionView collectionView, NSIndexPath indexPath)
            {

                Platform platform;
                string name;
                switch (indexPath.Row)
                {
                    case 0:
                        platform = platforms.Android;
                        name = "Android";
                        break;
                    case 1:
                        name = "iOS";
                        platform = platforms.Ios;
                        break;
                    default:
                        name = "Web";
                        platform = platforms.Web;
                        break;
                }

                var alert = UIAlertController.Create(name, JsonConvert.SerializeObject(platform), UIAlertControllerStyle.Alert);
                alert.AddAction(UIAlertAction.Create("Interesting", UIAlertActionStyle.Default, (actionOK) => { }));
                ViewController.NavigationController.PresentViewController(alert, true, null);
            }
        }
    }
}
