// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using SampleApp.iOS.ViewControllers.DetailViewControllers;
using UIKit;

namespace SampleApp.iOS
{
    public partial class ItemCollectionViewcController : UICollectionViewController
    {
        public ItemDetailViewModel ViewModel { get; set; }

        public ItemCollectionViewcController(IntPtr handle) : base(handle)
        {

        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            CollectionView.DataSource = new ItemDataSource(ViewModel);
            CollectionView.Delegate = new ItemDeletgateFlowLayout(ViewModel, this);
        }
    }
}
