// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using SDWebImage;
using UIKit;

namespace SampleApp.iOS
{
    public partial class ItemCollectionViewCell : UICollectionViewCell
    {

        public ItemCollectionViewCell(IntPtr handle) : base(handle)
        {
        }

        public void InitViews(string text)
        {
            ItemNameLabel.Text = text;

            SDImageCache.SharedImageCache.Config.ShouldCacheImagesInMemory = false;
            SDImageCache.SharedImageCache.ClearMemory();
            ItemImageView.SetImage(new NSUrl("https://picsum.photos/200/200"));
        }
    }
}
